<?php
$title = 'Automatización y funnels para pymes | La Llave de tu Pyme';
$description = 'Automatización y funnels para pymes: estrategia y ejecución conectadas con objetivos de negocio, decisiones claras y seguimiento continuo.';
$canonical = 'https://lallavedetupyme.com/servicios/automatizacion-y-funnels/';
$schemaJson = '[{"@context":"https://schema.org","@type":"Organization","name":"La Llave de tu Pyme","url":"https://lallavedetupyme.com","logo":"https://lallavedetupyme.com/assets/logo-la-llave.png","description":"Agencia de marketing digital para pymes: estrategia, web, SEO, publicidad, contenidos y automatización bajo una misma dirección."},{"@context":"https://schema.org","@type":"Service","name":"Automatización y funnels para pymes | La Llave de tu Pyme","url":"https://lallavedetupyme.com/servicios/automatizacion-y-funnels/","serviceType":"Automatización y funnels","provider":{"@type":"Organization","name":"La Llave de tu Pyme","url":"https://lallavedetupyme.com"},"areaServed":"España"}]';
require dirname(__DIR__) . '/partials/head.php';
require dirname(__DIR__) . '/partials/header.php';
?>
<main id="contenido">
    <section class="page-hero service-hero"><div class="container service-hero-grid"><div><a class="back-link" href="/servicios/">← Todos los servicios</a><span class="eyebrow">06 / Automatización y funnels</span><h1>Que ninguna oportunidad dependa de acordarse a tiempo</h1><p class="hero-lead">Diseñamos recorridos, automatizaciones y conexiones para que los contactos reciban la respuesta adecuada y el equipo mantenga el contexto sin perseguir tareas repetitivas.</p><a class="button" href="/contacto/">Hablar de este reto <span aria-hidden="true">↗</span></a></div><div class="service-hero-icon"><svg viewBox="0 0 48 48" aria-hidden="true"><path d="M6 8h36L29 23v12l-10 5V23L6 8Z"/><path d="M33 28a8 8 0 1 1-5 10M33 28v7h-7"/></svg><span>06</span></div></div></section>
    <section class="section service-problem"><div class="container split-intro"><div><span class="eyebrow">El punto de partida</span><h2>Primero entendemos qué está frenando el avance.</h2></div><div class="large-copy"><p>Cuando formularios, correos, campañas y seguimiento viven separados, las oportunidades se enfrían. Unimos los puntos y dejamos claro qué ocurre después de cada acción.</p><p class="service-fit"><strong>Encaja contigo si:</strong> Para equipos que generan oportunidades, pero pierden tiempo o información al moverlas entre herramientas y personas.</p></div></div></section>
    <section class="section deliverables-section"><div class="container section-heading"><div><span class="eyebrow">Qué ponemos en juego</span><h2>Una capacidad completa, ajustada al problema.</h2></div><p>No todas las fases necesitan el mismo peso. Definimos el alcance después de entender la situación.</p></div><div class="container deliverable-grid"><article data-reveal><span>01</span><h3>Mapa del recorrido comercial</h3></article><article data-reveal><span>02</span><h3>Funnels y secuencias</h3></article><article data-reveal><span>03</span><h3>Automatizaciones de seguimiento</h3></article><article data-reveal><span>04</span><h3>Integración de formularios y CRM</h3></article><article data-reveal><span>05</span><h3>Email y segmentación</h3></article><article data-reveal><span>06</span><h3>Medición de cada etapa</h3></article></div></section>
    <section class="section outcome-section"><div class="container outcome-panel"><div><span class="eyebrow">Lo que debería cambiar</span><h2>El trabajo se mide por el movimiento que produce.</h2></div><ul><li>Responder con más continuidad</li><li>Reducir tareas repetitivas</li><li>Conservar el contexto de cada contacto</li></ul></div></section>
    <section class="section working-section"><div class="container section-heading"><div><span class="eyebrow">Cómo avanzamos</span><h2>Con contexto, criterio y conversación.</h2></div></div><div class="container method-grid"><article class="method-step" data-reveal><span>01</span><h3>Entramos en el contexto</h3><p>Antes de proponer, entendemos qué vendes, cómo decides y dónde se atasca hoy el crecimiento.</p></article><article class="method-step" data-reveal><span>02</span><h3>Ponemos orden</h3><p>Convertimos ideas, urgencias y datos en una lista de prioridades que todo el mundo puede entender.</p></article><article class="method-step" data-reveal><span>03</span><h3>Hacemos que ocurra</h3><p>La estrategia no se queda en una presentación. Diseñamos, escribimos, configuramos, publicamos y medimos.</p></article><article class="method-step" data-reveal><span>04</span><h3>Seguimos cerca</h3><p>No desaparecemos entre reuniones. Si hay que decidir, corregir o aprovechar una oportunidad, abrimos la conversación.</p></article></div></section>
    <section class="section related-section"><div class="container section-heading"><div><span class="eyebrow">Capacidades que suelen conectar</span><h2>Ningún canal trabaja solo.</h2></div></div><div class="container service-grid compact"><a class="service-card" href="/servicios/estrategia-digital/"><span class="service-number">01</span><h3>Estrategia digital</h3><p>Primero decidimos qué merece tu tiempo y tu inversión.</p><span class="card-link">Ver servicio ↗</span></a><a class="service-card" href="/servicios/diseno-web/"><span class="service-number">02</span><h3>Diseño y desarrollo web</h3><p>Una web que explica, orienta y convierte.</p><span class="card-link">Ver servicio ↗</span></a><a class="service-card" href="/servicios/posicionamiento-seo/"><span class="service-number">03</span><h3>Posicionamiento SEO</h3><p>Visibilidad donde ya existe una intención de búsqueda.</p><span class="card-link">Ver servicio ↗</span></a></div></section>
    <section class="section cta-section">
    <div class="container cta-panel" data-reveal>
      <div><span class="eyebrow">Sin formularios mentales</span><h2>No necesitas tenerlo todo claro para empezar.</h2></div>
      <div><p>Cuéntanos qué quieres mover, qué has probado y dónde notas el atasco. Nosotros ponemos las preguntas que faltan.</p><a class="button button-light" href="/contacto/">Abrir una conversación <span aria-hidden="true">↗</span></a></div>
    </div>
  </section></main>
<?php
require dirname(__DIR__) . '/partials/footer.php';
