<?php
$title = 'Diseño y desarrollo web para pymes | La Llave de tu Pyme';
$description = 'Diseño y desarrollo web para pymes: estrategia y ejecución conectadas con objetivos de negocio, decisiones claras y seguimiento continuo.';
$canonical = 'https://lallavedetupyme.com/servicios/diseno-web/';
$schemaJson = '[{"@context":"https://schema.org","@type":"Organization","name":"La Llave de tu Pyme","url":"https://lallavedetupyme.com","logo":"https://lallavedetupyme.com/assets/logo-la-llave.png","description":"Agencia de marketing digital para pymes: estrategia, web, SEO, publicidad, contenidos y automatización bajo una misma dirección."},{"@context":"https://schema.org","@type":"Service","name":"Diseño y desarrollo web para pymes | La Llave de tu Pyme","url":"https://lallavedetupyme.com/servicios/diseno-web/","serviceType":"Diseño y desarrollo web","provider":{"@type":"Organization","name":"La Llave de tu Pyme","url":"https://lallavedetupyme.com"},"areaServed":"España"}]';
require dirname(__DIR__) . '/partials/head.php';
require dirname(__DIR__) . '/partials/header.php';
?>
<main id="contenido">
    <section class="page-hero service-hero"><div class="container service-hero-grid"><div><a class="back-link" href="/servicios/">← Todos los servicios</a><span class="eyebrow">02 / Diseño y desarrollo web</span><h1>Tu web debe hacer avanzar la conversación</h1><p class="hero-lead">Diseñamos sitios con una jerarquía clara, una identidad reconocible y recorridos que llevan al usuario desde la primera duda hasta la siguiente acción.</p><a class="button" href="/contacto/">Hablar de este reto <span aria-hidden="true">↗</span></a></div><div class="service-hero-icon"><svg viewBox="0 0 48 48" aria-hidden="true"><rect x="6" y="9" width="36" height="28" rx="2"/><path d="M6 17h36M13 13h.1M19 13h.1M12 24h10v7H12M27 24h9M27 30h7"/></svg><span>02</span></div></div></section>
    <section class="section service-problem"><div class="container split-intro"><div><span class="eyebrow">El punto de partida</span><h2>Primero entendemos qué está frenando el avance.</h2></div><div class="large-copy"><p>Una web puede ser bonita y seguir sin ayudar al negocio. Trabajamos el mensaje, la arquitectura, el diseño y la medición como una sola pieza para que no haya distancia entre lo que prometes y lo que el usuario encuentra.</p><p class="service-fit"><strong>Encaja contigo si:</strong> Para negocios que necesitan una web nueva o quieren dejar atrás una presencia digital que ya no representa su nivel real.</p></div></div></section>
    <section class="section deliverables-section"><div class="container section-heading"><div><span class="eyebrow">Qué ponemos en juego</span><h2>Una capacidad completa, ajustada al problema.</h2></div><p>No todas las fases necesitan el mismo peso. Definimos el alcance después de entender la situación.</p></div><div class="container deliverable-grid"><article data-reveal><span>01</span><h3>Arquitectura y mapa de contenidos</h3></article><article data-reveal><span>02</span><h3>Copy y propuesta de valor</h3></article><article data-reveal><span>03</span><h3>Diseño responsive</h3></article><article data-reveal><span>04</span><h3>Desarrollo y optimización</h3></article><article data-reveal><span>05</span><h3>Formularios y medición</h3></article><article data-reveal><span>06</span><h3>SEO técnico de lanzamiento</h3></article></div></section>
    <section class="section outcome-section"><div class="container outcome-panel"><div><span class="eyebrow">Lo que debería cambiar</span><h2>El trabajo se mide por el movimiento que produce.</h2></div><ul><li>Explicar mejor lo que haces</li><li>Reducir fricción antes del contacto</li><li>Convertir la web en un activo comercial</li></ul></div></section>
    <section class="section working-section"><div class="container section-heading"><div><span class="eyebrow">Cómo avanzamos</span><h2>Con contexto, criterio y conversación.</h2></div></div><div class="container method-grid"><article class="method-step" data-reveal><span>01</span><h3>Entramos en el contexto</h3><p>Antes de proponer, entendemos qué vendes, cómo decides y dónde se atasca hoy el crecimiento.</p></article><article class="method-step" data-reveal><span>02</span><h3>Ponemos orden</h3><p>Convertimos ideas, urgencias y datos en una lista de prioridades que todo el mundo puede entender.</p></article><article class="method-step" data-reveal><span>03</span><h3>Hacemos que ocurra</h3><p>La estrategia no se queda en una presentación. Diseñamos, escribimos, configuramos, publicamos y medimos.</p></article><article class="method-step" data-reveal><span>04</span><h3>Seguimos cerca</h3><p>No desaparecemos entre reuniones. Si hay que decidir, corregir o aprovechar una oportunidad, abrimos la conversación.</p></article></div></section>
    <section class="section related-section"><div class="container section-heading"><div><span class="eyebrow">Capacidades que suelen conectar</span><h2>Ningún canal trabaja solo.</h2></div></div><div class="container service-grid compact"><a class="service-card" href="/servicios/estrategia-digital/"><span class="service-number">01</span><h3>Estrategia digital</h3><p>Primero decidimos qué merece tu tiempo y tu inversión.</p><span class="card-link">Ver servicio ↗</span></a><a class="service-card" href="/servicios/posicionamiento-seo/"><span class="service-number">03</span><h3>Posicionamiento SEO</h3><p>Visibilidad donde ya existe una intención de búsqueda.</p><span class="card-link">Ver servicio ↗</span></a><a class="service-card" href="/servicios/publicidad-digital/"><span class="service-number">04</span><h3>Publicidad digital</h3><p>Campañas con intención, contexto y una página preparada para recibirlas.</p><span class="card-link">Ver servicio ↗</span></a></div></section>
    <section class="section cta-section">
    <div class="container cta-panel" data-reveal>
      <div><span class="eyebrow">Sin formularios mentales</span><h2>No necesitas tenerlo todo claro para empezar.</h2></div>
      <div><p>Cuéntanos qué quieres mover, qué has probado y dónde notas el atasco. Nosotros ponemos las preguntas que faltan.</p><a class="button button-light" href="/contacto/">Abrir una conversación <span aria-hidden="true">↗</span></a></div>
    </div>
  </section></main>
<?php
require dirname(__DIR__) . '/partials/footer.php';
